### ISSUE TITLE
Problem encountered after setting up Model 3

### ISSUE THREAD

**Issue by lingyun888** [nreusch/TSNConf#2]
When I set up Model 3, I found that the printed Found Schedule was 0. May I ask what the reason is?

**Comment by nreusch** [comment]
Hello @lingyun888,

what do you mean with Model 3?
Could you give me the command you are running and the output you receive?

**Comment by lingyun888** [comment]
command：python main.py .\testcases\TC3.2_medium.flex_network_description --mode 3 --visualize --no_security
output error：
![Snipaste_2024-03-11_09-20-32](https://github.com/nreusch/TSNConf/assets/75254187/a7914a7c-3867-471a-9809-761a080b1af7)
I debugged the code and found that the member variables in solution_object.tc.schedule are all empty.
![image](https://github.com/nreusch/TSNConf/assets/75254187/2493f7a3-b325-49c9-9f78-977d133ad575)

**Comment by nreusch** [comment]
Hello @lingyun888,

I can't quite manage to replicate your error on my setup. Could you share your codebase?
What optimization are you trying to run? I assume SA optimization, where routing & scheduling is combined?

**Comment by lingyun888** [comment]
Thank you for your reply. I didn't do any optimization, but I ran the program in the window system. I don't know if it's related to the environment.

**Comment by lingyun888** [comment]
Thank you for your reply. I forgot a little bit, there were many small issues when running SA optimization (-- model 3) in this code before, and it is possible that the current error is related to the previous error.

**Comment by lingyun888** [comment]
Hello, may I have your email

**Comment by nreusch** [comment]
Hello @lingyun888,

you were running into these issues because the main branch was using an outdated version of the tool, which did not have the SA heuristic properly implemented yet. I have now updated the main branch to the newest version and I can run the testcase with
```
python main.py testcases/TC3.2_medium.flex_network_description --mode 13 --visualize --no_security --timeout_scheduling 60
```

Be aware that there are a lot of changes now.
You can reach me via mail at nikre@dtu.dk.

Greetings
Niklas

**Comment by lingyun888** [comment]
Thank you very much for your help.
